### ISSUE TITLE
Error when enabling/disabling magnet card

### ISSUE THREAD

**Issue by Leonyx1175** [p455w0rd/WirelessCraftingTerminal#104]
This happens with and without the card installed in the WCT:
`[18:21:09] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at p455w0rd.wct.sync.packets.PacketSetMagnet.serverPacketData(PacketSetMagnet.java:46) ~[PacketSetMagnet.class:?]
        at p455w0rd.wct.sync.network.WCTServerPacketHandler$1.call(WCTServerPacketHandler.java:34) ~[WCTServerPacketHandler$1.class:?]
        at p455w0rd.wct.sync.WCTPacket.func_148833_a(WCTPacket.java:61) ~[WCTPacket.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2221-5.1.0-BETA-2136]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:156) ~[CauseTracker.class:1.10.2-2221-5.1.0-BETA-2136]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) ~[PacketUtil.class:1.10.2-2221-5.1.0-BETA-2136]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) ~[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
`
and with card in hand:

`[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at p455w0rd.wct.items.ItemMagnet.switchMagnetMode(ItemMagnet.java:236) ~[ItemMagnet.class:?]
        at p455w0rd.wct.items.ItemMagnet.func_77659_a(ItemMagnet.java:209) ~[ItemMagnet.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162) ~[adz.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2221-5.1.0-BETA-2136]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:156) ~[CauseTracker.class:1.10.2-2221-5.1.0-BETA-2136]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) ~[PacketUtil.class:1.10.2-2221-5.1.0-BETA-2136]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjf000(SourceFile:539) ~[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
`
There is also no chat message when switching between the modes.

I'm using SpongeForge, this error was caught using version 2221, build 2136 and it also happens with the latest, version 2160. Any other information needed?

**Comment by p455w0rd** [comment]
I usually don't support SF, but this has nothing to do with them. I'll get a fix out asap. TY :)

**Comment by Leonyx1175** [comment]
Still happens in WCT ver. 0.0.9, same error message.

**Comment by p455w0rd** [comment]
latest is 0.0.10..at any rate i'm testing and testing..just can't reproduced..definitely fixed on my end..I'll be pushing another update soon as there is another bug i've been made aware of

**Comment by Leonyx1175** [comment]
Sounds good, I'll push that update out on our modpack tonight or tomorrow morning and get back with you.

**Comment by p455w0rd** [comment]
hello..getting ready to push now..just wanted to let you know that I found a couple more spots where I was referencing I18n on both sides..it's client-side only, so that's why these crashes were happening and I've just found a couple more cases where this is happening..in v0.0.11 this issue should be resolved :) thanks for the heads up!

**Comment by Leonyx1175** [comment]
Alright, I'll hold off on pushing our update until 0.0.11 is ready, our update got delayed anyhow. Sorry I couldn't get back to you earlier on it, and thanks for the hard work with it too!

**Comment by p455w0rd** [comment]
it's already out :) follow me on Twitter (@TheRealp455w0rd) or join my discord to stay up to date - https://discord.gg/9J7yhUP
