### ISSUE TITLE
GUI doesn't open

### ISSUE THREAD

**Issue by TheRegulator** [p455w0rd/WirelessCraftingTerminal#114]
The server i play on got an update today, and now the GUI of the Terminal doesn't open anymore.

i tried version 0.0.8 with lib 1.0.12 and version 0.0.16 with lib 1.0.13
forge versions: 12.18.3.2239 and 12.18.3.2254

log:
[14:27:35] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at p455w0rd.wct.sync.packets.PacketMEInventoryUpdate.clientPacketData(PacketMEInventoryUpdate.java:112) ~[PacketMEInventoryUpdate.class:?]
	at p455w0rd.wct.sync.network.WCTClientPacketHandler$1.call(WCTClientPacketHandler.java:34) ~[WCTClientPacketHandler$1.class:?]
	at p455w0rd.wct.sync.WCTPacket.func_148833_a(WCTPacket.java:61) ~[WCTPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 17 more

**Comment by BloodWorkXGaming** [comment]
Can confirm this.


`[Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at p455w0rd.wct.handlers.GuiHandler.getClientGuiElement(GuiHandler.java:85) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:58) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.access$000(OpenGuiHandler.java:34) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$1.run(OpenGuiHandler.java:49) ~[OpenGuiHandler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more`

**Comment by p455w0rd** [comment]
is the server running sponge by chance for either of you?

**Comment by BloodWorkXGaming** [comment]
Ours is, ye. Is that causing issues?

p455w0rd <notifications@github.com> schrieb am Mo., 13. März 2017, 00:55:

**Comment by p455w0rd** [comment]
from what I can tell, yes..this keeps coming up on sponge servers..nothing I can really do about this..if you remove sponge and can confirm this is still a bug, I'll look into it

**Comment by BloodWorkXGaming** [comment]
Okey, thanks, gonna ask the owner of the server to remove it to test it.
Can tell you more tomorrow or in 2 days.

p455w0rd <notifications@github.com> schrieb am Mo., 13. März 2017, 00:58:

**Comment by BloodWorkXGaming** [comment]
Sorry, was mistaking, we had Sponge at the start of the server, but it got removed since then. 
So there was no sponge on the server while I tried to use it.

**Comment by BloodWorkXGaming** [comment]
Sorry to bother you. 
Any news on this issue or should we just revert to a older version or will that cause other issues?

**Comment by p455w0rd** [comment]
I am out of town tm..heading home tonight. I'll be able to look further into this then

**Comment by p455w0rd** [comment]
ok, so I need a pack name or modlist and I will do my best to geta fix out today if I get this info fast enough

**Comment by p455w0rd** [comment]
ok..i'll DL and create a new instance with the current WCT version and see if I can fix this..WCT (afaik) works great in FTB Beyond and they have a full team of testers, so I'm hoping it's interaction with another mod in which case I can submit a PR and hopefully get this fixed

**Comment by p455w0rd** [comment]
found the source of the error..total derpon my part when updating to new MouseTweaks API..testing now..if all goes well, I'll have a version up on curse ASAP :)

**Comment by BloodWorkXGaming** [comment]
Cool, thank you ^^

p455w0rd <notifications@github.com> schrieb am Do., 16. März 2017, 14:54:

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2393752-i'll try and contact whatthedrunk about the update

**Comment by BloodWorkXGaming** [comment]
Can do that myself, I am on close contact with one of the devs

p455w0rd <notifications@github.com> schrieb am Do., 16. März 2017, 15:02:

**Comment by BloodWorkXGaming** [comment]
Just wrote with PotDucky, he will add the new version in the next update
cycle which should be around next week or so.

BloodWorkXGaming . <bloodworkxgaming@gmail.com> schrieb am Do., 16. März
2017, 15:03:

**Comment by p455w0rd** [comment]
Thanks :)
