### ISSUE TITLE
GUI doesn't open

### ISSUE THREAD

**Issue by lschad** [p455w0rd/WirelessCraftingTerminal#245]
Using **WirelessCraftingTerminal-1.10.2-2.1.39.jar**, modpack is [Age of Engineering 1.1.2](https://minecraft.curseforge.com/projects/age-of-engineering/files/2503175)

RMB on the Crafting Terminal does nothing - although it spits out the following exception. I found #114 although this kinda seems to be a different issue? Not sure. 

```
[13:51:16] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: p455w0rd/wct/client/gui/GuiWCT
	at p455w0rd.wct.handlers.GuiHandler.getClientGuiElement(GuiHandler.java:85) ~[GuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.process(OpenGuiHandler.java:58) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler.access$000(OpenGuiHandler.java:34) ~[OpenGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.OpenGuiHandler$1.run(OpenGuiHandler.java:49) ~[OpenGuiHandler$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more
```

**Comment by lschad** [comment]
🙄 
my bad. it seems AoE was using an outdated mouse tweaks

**Comment by p455w0rd** [comment]
Please use a service like one of the following when posting logs (just for future reference):
- [GitHub Gist](http://gist.github.com/)
- [Pastebin](http://www.pastebin.com/)

Also, WCT for 1.10.2 has been updated with a fix for the ExtraCells 2Mekanism/Thermal Expansion crashes. You can get the update [here](https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2538109).
