### ISSUE TITLE
Terminal cannot insert or extract items

### ISSUE THREAD

**Issue by a20eac1d** [p455w0rd/WirelessCraftingTerminal#295]
I can open the WCT and see the content of my ME system.
When I try to insert or extract items, nothing happens.

I am using the latest version of AE2, P455w0rd's Lib and WCT, all downloaded just now from Curseforge.

Server console output:

```
[08:28:32] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: appeng.api.storage.channels.IItemStorageChannel.poweredExtraction(Lappeng/api/networking/energy/IEnergySource;Lappeng/api/storage/IMEInventory;Lappeng/api/storage/data/IAEStack;Lappeng/api/networking/security/IActionSource;)Lappeng/api/storage/data/IAEStack;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: appeng.api.storage.channels.IItemStorageChannel.poweredExtraction(Lappeng/api/networking/energy/IEnergySource;Lappeng/api/storage/IMEInventory;Lappeng/api/storage/data/IAEStack;Lappeng/api/networking/security/IActionSource;)Lappeng/api/storage/data/IAEStack;
        at p455w0rd.wct.container.ContainerWCT.doAction(ContainerWCT.java:509) ~[ContainerWCT.class:?]
        at p455w0rd.wct.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:153) ~[PacketInventoryAction.class:?]
        at p455w0rd.wct.sync.network.WCTServerPacketHandler$1.call(WCTServerPacketHandler.java:49) ~[WCTServerPacketHandler$1.class:?]
        at p455w0rd.wct.sync.WCTPacket.processPacket(WCTPacket.java:97) ~[WCTPacket.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
```

**Comment by BrisingrAerowing** [comment]
You are using the release version, which only supports RV5. Update to the latest 3.10 beta, as that is for AE2-RV6.

**Comment by p455w0rd** [comment]
@BrisingrAerowing is correct here :) new version in progress
