### ISSUE TITLE
Crash at boot with ExtraCells and Baubles installed

### ISSUE THREAD

**Issue by LemADEC** [p455w0rd/WirelessCraftingTerminal#302]
As of WirelessCraftingTerminal-1.12.2-3.11.83, with Baubles-1.12-1.5.2, ExtraCells-1.12.2-2.6.1a, game will crash at boot as long as those 3 mods are installed.
Downgrading to WirelessCraftingTerminal-1.12.2-3.10.82 will allow to boot the game.

```
Description: Initializing game

java.lang.AbstractMethodError: Method extracells/item/ItemWirelessTerminalUniversal$.getBaubleType(Lnet/minecraft/item/ItemStack;)Lbaubles/api/BaubleType; is abstract
	at extracells.item.ItemWirelessTerminalUniversal$.getBaubleType(ItemWirelessTerminalUniversal.scala)
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_59_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:335)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

https://gist.github.com/LemADEC/6f438bf21fa9f5c34273336ec158aad7

**Comment by BrockWS** [comment]
Extra Cells 2 needs to be updated. Already reported. ExtraCells/ExtraCells2#619

**Comment by p455w0rd** [comment]
should be fixed in latest EC2 update

**Comment by NyxCode** [comment]
@p455w0rd 
The newest version of FTB Revelation (ExtraCells-1.12.2-2.6.2a) still has this exact issue.

**Comment by p455w0rd** [comment]
yes..this is because I do not have access to the CurseForge account for EC2. You can get a version with this fixed on my discord server in the #extracells-2 channel. Soon there will no longer be a need for EC2...REALLY soon :)

**Comment by NyxCode** [comment]
Oh, that's great! EC2 is just PACKED with bugs like this..
