### ISSUE TITLE
Server bug on open remote

### ISSUE THREAD

**Issue by gungun974** [p455w0rd/WirelessCraftingTerminal#303]
Hello i have found a bug with the last version of wireless crafting terminal
When i use the remote on a server my inventory change like this :
![image](https://user-images.githubusercontent.com/5224459/50301831-a44bb880-0488-11e9-8305-d5ab1d7efc2d.png)

The remote works only in the first slot and other slot the remote make that error :

`[18:12:59] [main/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 46, Size: 46
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_181]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120) ~[afr.class:?]
	at net.minecraft.inventory.Container.func_190896_a(Container.java:527) ~[afr.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1191) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:50) ~[is.class:?]
	at net.minecraft.network.play.server.SPacketWindowItems.func_148833_a(SourceFile:12) ~[is.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 17 more`

**Comment by gungun974** [comment]
For more details this is the mods i use :
`Mods:
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.3
  alchemistry-0.7.13
  alib-1.0.2
  alternatingflux-0.12.2-1
  appliedenergistics2-rv6-stable-4
  architecturecraft-1.12-3.80
  Aroma1997Core-1.12.2-2.0.0.0
  Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
  Avaritia-1.13
  bdlib-1.14.3.12-mc1.12.2
  BrandonsCore-1.12.2-2.4.7.189-universal
  ChickenChunks-1.12.2-2.4.1.73-universal
  Chisel-MC1.12.2-0.2.1.35
  chiselsandbits-14.29
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CoFHCore-1.12.2-4.6.1.22-universal
  CoFHWorld-1.12.2-1.3.0.6-universal
  ComputerCraft1.80pr1
  Computronics-1.12.1-1.6.5
  CTM-MC1.12.2-0.3.2.20
  davincisvessels-1.12-6.340-full
  Draconic-Evolution-1.12.2-2.3.17.321-universal
  EnderCore-1.12.2-0.5.43
  EnderIO-1.12.2-5.0.38
  EnderStorage-1.12.2-2.4.5.135-universal
  ExtraBitManipulation-1.12.2-3.4.1
  extrautils2-1.12-1.9.8
  ExtremeReactors-1.12.2-0.4.5.49
  foamfix-0.10.3-1.12.2
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.0.79-universal
  gravestone-1.10.2
  IGW-Mod-1.12.2-1.4.4-15-universal
  ImmersiveEngineering-0.12-86
  immersivepetroleum-1.12.2-1.1.9
  ironchest-1.12.2-7.0.40.824
  jei_1.12.2-4.13.1.225
  jepb-1.12-1.2.1
  journeymap-1.12.2-5.5.3
  JustEnoughPetroleum-0.1
  LaserLevel-1.12.2-2.1.0.19-universal
  LunatriusCore-1.12.2-1.2.0.42-universal
  Mantle-1.12-1.3.3.39
  mcjtylib-1.12-3.0.7
  MCMultiPart-2.5.3
  Mekanism-1.12.2-9.4.3.330
  MekanismGenerators-1.12.2-9.4.3.330
  MekanismTools-1.12.2-9.4.3.330
  moreoverlays-1.14-mc1.12.2
  movingworld-1.12-6.342-full
  MrTJPCore-1.12.2-2.1.3.35-universal
  ocsensors-1.0.4-b23
  OpenComputers-MC1.12.2-1.7.3.146
  OpenGlasses-MC1.12.2-2.0.0
  OpenSecurity-MC1.12.2-1.0-12
  p455w0rdslib-1.12-2.0.35
  ProjectRed-1.12.2-4.9.1.92-Base
  ProjectRed-1.12.2-4.9.1.92-compat
  ProjectRed-1.12.2-4.9.1.92-fabrication
  ProjectRed-1.12.2-4.9.1.92-integration
  ProjectRed-1.12.2-4.9.1.92-lighting
  ProjectRed-1.12.2-4.9.1.92-mechanical
  ProjectRed-1.12.2-4.9.1.92-world
  RebornCore-1.12.2-3.10.5.350-universal
  RedstoneFlux-1.12-2.1.0.6-universal
  rftools-1.12-7.59
  rftoolsctrl-1.12-1.9.2
  rftoolsdim-1.12-5.63
  rftpwr_oc-0.2
  Schematica-1.12.2-1.8.0.169-universal
  SGCraft-1.3-mc1.12.2
  Signals-1.12.2-1.3.13-28-universal
  Simple-Void-World-1.12-1.2.0.9-universal
  SolarFluxReborn_1.12.2-4.16r
  TConstruct-1.12.2-2.11.0.106
  ThermalCultivation-1.12.2-0.3.1.8-universal
  ThermalDynamics-1.12.2-2.5.3.16-universal
  ThermalExpansion-1.12.2-5.5.2.39-universal
  ThermalFoundation-1.12.2-2.6.1.22-universal
  ThermalInnovation-1.12.2-0.3.1.8-universal
  TinkerToolLeveling-1.12.2-1.1.0
  TIS-3D-MC1.12.2-1.5.0.34
  torchmaster_1.12.2-1.6.4.62
  Treecapitator-1.12-at_0.9a
  WirelessCraftingTerminal-1.12.2-3.11.84
  zerocore-1.12-0.1.2.2`

**Comment by gungun974** [comment]
For more details this is the mods i use :
Mods:
- ae2stuf
- f-0.7.0.4-mc1.12.2
-   AE2WTLib-1.12.2-1.0.3
-   alchemistry-0.7.13
-   alib-1.0.2
-   alternatingflux-0.12.2-1
-   appliedenergistics2-rv6-stable-4
-   architecturecraft-1.12-3.80
-   Aroma1997Core-1.12.2-2.0.0.0
-   Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
-   Avaritia-1.13
-   bdlib-1.14.3.12-mc1.12.2
-   BrandonsCore-1.12.2-2.4.7.189-universal
-   ChickenChunks-1.12.2-2.4.1.73-universal
-   Chisel-MC1.12.2-0.2.1.35
-   chiselsandbits-14.29
-   CodeChickenLib-1.12.2-3.2.2.353-universal
-   CoFHCore-1.12.2-4.6.1.22-universal
-   CoFHWorld-1.12.2-1.3.0.6-universal
-   ComputerCraft1.80pr1
-   Computronics-1.12.1-1.6.5
-   CTM-MC1.12.2-0.3.2.20
-   davincisvessels-1.12-6.340-full
-   Draconic-Evolution-1.12.2-2.3.17.321-universal
-   EnderCore-1.12.2-0.5.43
-   EnderIO-1.12.2-5.0.38
-   EnderStorage-1.12.2-2.4.5.135-universal
-   ExtraBitManipulation-1.12.2-3.4.1
-   extrautils2-1.12-1.9.8
-   ExtremeReactors-1.12.2-0.4.5.49
-   foamfix-0.10.3-1.12.2
-   Forgelin-1.8.2
-   ForgeMultipart-1.12.2-2.6.0.79-universal
-   gravestone-1.10.2
-   IGW-Mod-1.12.2-1.4.4-15-universal
-   ImmersiveEngineering-0.12-86
-   immersivepetroleum-1.12.2-1.1.9
-   ironchest-1.12.2-7.0.40.824
-   jei_1.12.2-4.13.1.225
-   jepb-1.12-1.2.1
-   journeymap-1.12.2-5.5.3
-   JustEnoughPetroleum-0.1
-   LaserLevel-1.12.2-2.1.0.19-universal
-   LunatriusCore-1.12.2-1.2.0.42-universal
-   Mantle-1.12-1.3.3.39
-   mcjtylib-1.12-3.0.7
-   MCMultiPart-2.5.3
-   Mekanism-1.12.2-9.4.3.330
-   MekanismGenerators-1.12.2-9.4.3.330
-   MekanismTools-1.12.2-9.4.3.330
-   moreoverlays-1.14-mc1.12.2
-   movingworld-1.12-6.342-full
-   MrTJPCore-1.12.2-2.1.3.35-universal
-   ocsensors-1.0.4-b23
-   OpenComputers-MC1.12.2-1.7.3.146
-   OpenGlasses-MC1.12.2-2.0.0
-   OpenSecurity-MC1.12.2-1.0-12
-   p455w0rdslib-1.12-2.0.35
-   ProjectRed-1.12.2-4.9.1.92-Base
-   ProjectRed-1.12.2-4.9.1.92-compat
-   ProjectRed-1.12.2-4.9.1.92-fabrication
-   ProjectRed-1.12.2-4.9.1.92-integration
-   ProjectRed-1.12.2-4.9.1.92-lighting
-   ProjectRed-1.12.2-4.9.1.92-mechanical
-   ProjectRed-1.12.2-4.9.1.92-world
-   RebornCore-1.12.2-3.10.5.350-universal
-   RedstoneFlux-1.12-2.1.0.6-universal
-   rftools-1.12-7.59
-   rftoolsctrl-1.12-1.9.2
-   rftoolsdim-1.12-5.63
-   rftpwr_oc-0.2
-   Schematica-1.12.2-1.8.0.169-universal
-   SGCraft-1.3-mc1.12.2
-   Signals-1.12.2-1.3.13-28-universal
-   Simple-Void-World-1.12-1.2.0.9-universal
-   SolarFluxReborn_1.12.2-4.16r
-   TConstruct-1.12.2-2.11.0.106
-   ThermalCultivation-1.12.2-0.3.1.8-universal
-   ThermalDynamics-1.12.2-2.5.3.16-universal
-   ThermalExpansion-1.12.2-5.5.2.39-universal
-   ThermalFoundation-1.12.2-2.6.1.22-universal
-   ThermalInnovation-1.12.2-0.3.1.8-universal
-   TinkerToolLeveling-1.12.2-1.1.0
-   TIS-3D-MC1.12.2-1.5.0.34
-   torchmaster_1.12.2-1.6.4.62
-   Treecapitator-1.12-at_0.9a
-   WirelessCraftingTerminal-1.12.2-3.11.84
-   zerocore-1.12-0.1.2.2

**Comment by p455w0rd** [comment]
verified, reproduced, and fixed in dev. thank you
