### ISSUE TITLE
Deposit crashes the game

### ISSUE THREAD

**Issue by Buzingo** [p455w0rd/WirelessCraftingTerminal#312]
So as soon as I want to deposit an Item to  my ME via the WCT, nothing happens.. so I tried to force the WCT to add the item to the ME via a Magnet card. As soon as the magnet card tries to add the item to the ME, my game Crashes.. we are playing on a multiplayer server and the modpack is FTB Sky Adventures

**Comment by p455w0rd** [comment]
crash report/log?

**Comment by Buzingo** [comment]
> crash report/log?

and this might be the exception out of the server log

`net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: appeng.api.storage.channels.IItemStorageChannel.poweredInsert(Lappeng/api/networking/energy/IEnergySource;Lappeng/api/storage/IMEInventory;Lappeng/api/storage/data/IAEStack;Lappeng/api/networking/security/IActionSource;)Lappeng/api/storage/data/IAEStack;
	at p455w0rd.wct.items.ItemMagnet.doInject(ItemMagnet.java:512) ~[ItemMagnet.class:?]
	at p455w0rd.wct.items.ItemMagnet.doMagnet(ItemMagnet.java:333) ~[ItemMagnet.class:?]
	at p455w0rd.wct.init.ModEvents.tickEvent(ModEvents.java:151) ~[ModEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1152_ModEvents_tickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more`

**Comment by p455w0rd** [comment]
I would need the full log and please use a service like GitHub gist or pastebin for long pastes like there. I need to know what  AE version you're running and what WCT version you're running. The references in this log tell me that you must be running an outdated version of WCT.
