### ISSUE TITLE
Magnet card breaks player on servers

### ISSUE THREAD

**Issue by NanoCats** [p455w0rd/WirelessCraftingTerminal#317]
I crafted a magnet card and installed it on the crafting terminal while out and about and it crashes the player out of the server, the server itself is fine. `(Internal Exception:Java.io.IOException: An existing connection was forcibly closed by the remote host` or simply "Internal Server Error") 

`[19:03:15] [Netty Client IO #3/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_171]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

is all I have from the logs. 

I'm currently working on getting the log files from the server, as I do not own it, 

Furthermore I'm experiencing difficulties where I can only use it as a bauble, it (The terminal) shuffles my inventory randomly if I try to use it by right clicking, this doesn't crash me or generate an error though...

These issues only appear to happen on servers.

**Comment by p455w0rd** [comment]
could you provide me with a server log snippet of what happens server-side when a player gets disconnected?
