### ISSUE TITLE
Crash image 

### ISSUE THREAD

**Issue by dagantang** [p455w0rd/WirelessCraftingTerminal#361]
![2019-11-17_01 36 49](https://user-images.githubusercontent.com/32885622/68997827-c4c50280-08e5-11ea-88a3-762de61040e7.png)

**Comment by dagantang** [comment]
![2019-11-17_02 56 44](https://user-images.githubusercontent.com/32885622/68997844-ea520c00-08e5-11ea-92c0-8a44a2ff5bfd.png)

**Comment by Protheus** [comment]
I have the same issue with the latest version: https://pastebin.com/Swv7dtsU

Texture is missing, and the moment you use it, the crash happens.

- AE2WTLib-1.12.2-1.0.32
- p455w0rdslib-1.12.2-2.2.156
- WirelessCraftingTerminal-1.12.2-3.12.96
- WirelessFluidTerminal-1.12.2-1.0.2
- WirelessInterfaceTerminal-1.12.2-1.0.1
- WirelessPatternTerminal-1.12.2-1.0.2

-----
java.lang.NullPointerException: Registering texture
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:44)
	at p455w0rd.wpt.client.gui.GuiWPT.drawBG(GuiWPT.java:292)
	at p455w0rd.ae2wtlib.api.client.gui.GuiWT.func_146976_a(GuiWT.java:261)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at p455w0rd.ae2wtlib.api.client.gui.GuiWT.func_73863_a(GuiWT.java:167)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BedrockLegends** [comment]
same issue @p455w0rd will have to fix it

**Comment by Guest-87** [comment]
same issue @p455w0rd will have to fix it
