### ISSUE TITLE
Wireless crafting terminal doesn't open on server

### ISSUE THREAD

**Issue by Skyatails** [p455w0rd/WirelessCraftingTerminal#372]
As the title says, the wireless crafting terminal doesn't open on a server although it does work on a local world, using latest version of all dependencies and mods.

Forge 1.12.2 - 14.23.5.2847
p455w0rdslib-1.12.2-2.3.161
appliedenergistics2-rv6-stable-7
AE2WTLib-1.12.2-1.0.34
WirelessCraftingTerminal-1.12.2-3.12.97

Here's the crash log from the server, the client doesn't generate an error:

[Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_241]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.setPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/String;)V
	at p455w0rd.ae2wtlib.api.container.ContainerWT.<init>(ContainerWT.java:85) ~[ContainerWT.class:?]
	at p455w0rd.wct.container.ContainerWCT.<init>(ContainerWCT.java:101) ~[ContainerWCT.class:?]
	at p455w0rd.wct.init.ModGuiHandler.getServerGuiElement(ModGuiHandler.java:80) ~[ModGuiHandler.class:?]
	at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at p455w0rd.wct.init.ModGuiHandler.open(ModGuiHandler.java:155) ~[ModGuiHandler.class:?]
	at p455w0rd.wct.sync.packets.PacketOpenGui.serverPacketData(PacketOpenGui.java:60) ~[PacketOpenGui.class:?]
	at p455w0rd.wct.sync.network.WCTServerPacketHandler$1.call(WCTServerPacketHandler.java:49) ~[WCTServerPacketHandler$1.class:?]
	at p455w0rd.wct.sync.WCTPacket.func_148833_a(WCTPacket.java:95) ~[WCTPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_241]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

Full log pastebin:
https://pastebin.com/TM3CDSSZ

**Comment by Skyatails** [comment]
OK, found the problem.
In the server.bat I was still using an old version of forge (2772), not the new one (2847).
Sorry for the inconvenience.
