### ISSUE TITLE
NullPointerException when searching in creative crafting grid

### ISSUE THREAD

**Issue by Spongman** [p455w0rd/WirelessCraftingTerminal#81]
this happened in a creative world when searching in the creative crafting grid. i didn't have any WCT blocks/items crafted, or placed in my world.

i believe the problems is caused when ItemMagnet.addInformation is called when ItemMagnet.getItemStack() returns null. the subsequent call to ItemMagnet.isActivated() doesn't check for null and crashes.

````
	at net.p455w0rd.wirelesscraftingterminal.items.ItemMagnet.isActivated(ItemMagnet.java:527)
	at net.p455w0rd.wirelesscraftingterminal.items.ItemMagnet.func_77624_a(ItemMagnet.java:120)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73869_a(GuiContainerCreative.java:316)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
````

**Comment by Spongman** [comment]
this was in the project ozone 2 modpack.
